import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy - Poma AI",
  description: "Privacy policy for Poma AI. Learn how we handle your data.",
}

export default function PrivacyPage() {
  return (
    <div className="px-6 py-16 md:py-24">
      <div className="mx-auto max-w-3xl">
        <h1 className="border-b border-border pb-6 text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
          Privacy Policy
        </h1>

        <div className="prose prose-lg mt-12 text-muted-foreground prose-headings:text-foreground prose-strong:text-foreground prose-th:text-foreground prose-h2:mt-12 prose-h2:border-t prose-h2:border-border prose-h2:pt-8 prose-h3:mt-8 prose-h3:mb-3 prose-h4:mt-6 prose-h4:mb-2 prose-p:leading-relaxed prose-li:leading-relaxed prose-table:border prose-table:border-border prose-td:border prose-td:border-border prose-td:p-3 prose-th:border prose-th:border-border prose-th:p-3 prose-th:bg-secondary prose-a:text-primary">
          <p className="text-sm italic">Last updated: March 14, 2026</p>

          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2>Interpretation and Definitions</h2>

          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The
            following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &ldquo;control&rdquo; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Application</strong> refers to any application or software program provided by the Company, including but not limited to Poma AI, and any other applications or software programs provided by the Company.</li>
            <li><strong>Company</strong> (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or &ldquo;Our&rdquo; in this Agreement) refers to Bare Mitt AS. The Company acts as the Data Controller for the purposes of applicable data protection legislation, including the EU General Data Protection Regulation (GDPR) and the Norwegian Personal Data Act (Personopplysningsloven).</li>
            <li><strong>Country</strong> refers to: Norway</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2>Legal Basis for Processing (GDPR)</h2>
          <p>
            If You are located in the European Economic Area (EEA), including Norway, We process Your Personal Data based
            on the following legal grounds:
          </p>
          <ul>
            <li><strong>Performance of a contract:</strong> Processing is necessary to provide You with the Service, including meal analysis and score tracking.</li>
            <li><strong>Consent:</strong> Where You have given consent for specific processing activities, such as granting camera and photo library access.</li>
            <li><strong>Legitimate interests:</strong> Processing is necessary for Our legitimate interests, such as improving the Service, preventing fraud, and ensuring security, provided these interests do not override Your rights and freedoms.</li>
          </ul>
          <p>
            You have the right to withdraw consent at any time, without affecting the lawfulness of processing carried out
            prior to withdrawal.
          </p>

          <h2>Collecting and Using Your Personal Data</h2>

          <h3>Types of Data Collected</h3>

          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can
            be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul>
            <li>Email address</li>
            <li>Name</li>
            <li>Date of birth</li>
            <li>Gender</li>
            <li>Height and weight</li>
            <li>Dietary preferences and allergies</li>
            <li>Activity level</li>
          </ul>

          <h4>Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your
            Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service
            that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically,
            including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address
            of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device
            identifiers and other diagnostic data.
          </p>

          <h4>Camera and Photo Library Data</h4>
          <p>
            To provide our core meal analysis features, Our Application requires access to Your device&apos;s camera and photo
            library. If You grant permission, We collect the images You capture or upload within the Application. These
            images are securely transmitted to third-party artificial intelligence services (currently Google Gemini) solely
            for the purpose of analyzing the meal, generating nutritional and biological impact estimates, and providing
            feedback. We do not use Your images to train AI models, nor do we sell Your images to third parties. You can
            revoke camera and photo library access at any time via Your device settings.
          </p>

          <h4>Subscription and Payment Data</h4>
          <p>
            We use RevenueCat, Inc. as a third-party service to manage in-app subscriptions and purchases. When You
            subscribe to the Service, RevenueCat processes Your purchase through the Apple App Store. We receive
            subscription status information (such as whether You have an active subscription, trial status, and expiration
            dates) from RevenueCat, but We do not receive or store Your payment card details or billing information.
            RevenueCat&apos;s privacy policy is available at https://www.revenuecat.com/privacy.
          </p>

          <h2>Third-Party Service Providers</h2>
          <p>We use the following third-party services to operate and improve the Application:</p>
          <div className="overflow-x-auto">
            <table>
              <thead>
                <tr>
                  <th>Service</th>
                  <th>Provider</th>
                  <th>Purpose</th>
                  <th>Data Shared</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>Database &amp; Authentication</strong></td>
                  <td>Supabase, Inc.</td>
                  <td>User accounts, data storage, real-time sync</td>
                  <td>Account data, meal data, scores</td>
                </tr>
                <tr>
                  <td><strong>AI Meal Analysis</strong></td>
                  <td>Google (Gemini API)</td>
                  <td>Analyzing meal photos and generating biological impact scores</td>
                  <td>Meal images, meal descriptions</td>
                </tr>
                <tr>
                  <td><strong>Subscription Management</strong></td>
                  <td>RevenueCat, Inc.</td>
                  <td>Managing in-app purchases and subscription status</td>
                  <td>User ID, purchase receipts</td>
                </tr>
                <tr>
                  <td><strong>Push Notifications</strong></td>
                  <td>Expo (Expo Push)</td>
                  <td>Sending notifications about meal analysis results</td>
                  <td>Device push tokens</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h2>Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
          </ul>

          <h2>Retention of Your Personal Data</h2>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
            Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
            obligations, resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p>
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a
            shorter period of time, except when this data is used to strengthen the security or to improve the functionality
            of Our Service, or We are legally obligated to retain this data for longer time periods.
          </p>

          <h2>Transfer of Your Personal Data</h2>
          <p>
            Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other
            places where the parties involved in the processing are located. It means that this information may be
            transferred to, and maintained on, computers located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
          </p>
          <p>
            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to
            that transfer.
          </p>
          <p>
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
            accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or
            a country unless there are adequate controls in place including the security of Your data and other personal
            information.
          </p>

          <h2>Your Data Protection Rights (GDPR)</h2>
          <p>
            If You are located in the European Economic Area (EEA), including Norway, You have the following rights:
          </p>
          <ul>
            <li><strong>Right of access:</strong> You have the right to request copies of Your Personal Data.</li>
            <li><strong>Right to rectification:</strong> You have the right to request that We correct any information You believe is inaccurate or complete information You believe is incomplete.</li>
            <li><strong>Right to erasure:</strong> You have the right to request that We erase Your Personal Data, under certain conditions.</li>
            <li><strong>Right to restrict processing:</strong> You have the right to request that We restrict the processing of Your Personal Data, under certain conditions.</li>
            <li><strong>Right to data portability:</strong> You have the right to request that We transfer the data that We have collected to another organization, or directly to You, under certain conditions.</li>
            <li><strong>Right to object:</strong> You have the right to object to Our processing of Your Personal Data, under certain conditions.</li>
          </ul>
          <p>
            To exercise any of these rights, please contact Us at the details provided below. We will respond to Your
            request within 30 days. If You believe that We have not adequately addressed Your concerns, You have the right
            to lodge a complaint with the Norwegian Data Protection Authority (Datatilsynet) at https://www.datatilsynet.no.
          </p>

          <h2>Delete Your Personal Data</h2>
          <p>
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected
            about You. Our Service may give You the ability to delete certain information about You from within the Service.
          </p>
          <p>
            You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one,
            and visiting the account settings section that allows you to manage Your personal information. You may also
            contact Us to request access to, correct, or delete any personal information that You have provided to Us.
          </p>
          <p>
            Please note, however, that We may need to retain certain information when we have a legal obligation or lawful
            basis to do so.
          </p>

          <h2>Disclosure of Your Personal Data</h2>

          <h3>Business Transactions</h3>
          <p>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We
            will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
          </p>

          <h3>Law enforcement</h3>
          <p>
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by
            law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </p>

          <h3>Other legal requirements</h3>
          <p>
            The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
          </p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h2>Security of Your Personal Data</h2>
          <p>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the
            Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means
            to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <h2>Children&apos;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
            information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child
            has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental consent, We take steps to remove that
            information from Our servers.
          </p>
          <p>
            If We need to rely on consent as a legal basis for processing Your information and Your country requires consent
            from a parent, We may require Your parent&apos;s consent before We collect and use that information.
          </p>

          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link,
            You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every
            site You visit. We have no control over and assume no responsibility for the content, privacy policies or
            practices of any third party sites or services.
          </p>

          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy
            Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the
            change becoming effective and update the &ldquo;Last updated&rdquo; date at the top of this Privacy Policy. You are advised
            to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when
            they are posted on this page.
          </p>

          <h2>Contact us</h2>
          <p>
            If you have any questions about this Privacy Policy, You can contact us by email:{" "}
            <a href="mailto:magnus@baremitt.no" className="text-primary hover:underline">magnus@baremitt.no</a>
          </p>
        </div>
      </div>
    </div>
  )
}
